export const TRANSLATIONS = {
  en: {
    profile: "Profile",
    settingsSub: "Settings & preferences",
    journeyLog: "Journey Log",
    travelHistory: "Your travel history",
    tripsRecorded: "trips recorded",
    syncing: "Syncing...",
    noJourneysYet: "No journeys yet",
    startFirstTrip:
      "Start your first trip from the Explore tab and your journeys will appear here.",
    recentJourneys: "Recent journeys",
    deleteTripTitle: "Delete trip?",
    deleteTripSub: "This cannot be undone.",
    cancel: "Cancel",
    delete: "Delete",
    logTrip: "Log Trip",
    searchDestinations: "Search destinations...",
    origin: "Origin",
    destination: "Destination",
    satellite: "Satellite",
    map: "Map",
    journeyInProgress: "Journey in progress",
    startJourney: "Start Journey",
    endJourney: "End Journey",
    tripDetails: "Trip Details",
    fillTripInfo: "Fill in your trip info",
    from: "From",
    to: "To",
    enterFrom: "Enter start location",
    enterTo: "Enter destination",
    skipForNow: "Skip for now",
    saveJourney: "Save Journey",
    missingInfo: "Missing info",
    selectModeAlert: "Please select a transport mode.",
    journeyLoggedTitle: "Journey Logged! 🎉",
    awardXpMsg:
      "Successfully recorded path details via Vazhi.\n\nYou have been awarded +{points} XP for choosing this configuration.",
    transportMode: "Transport Mode",
    tripPurpose: "Trip Purpose",
    frequencyQuestion: "How often do you make this trip?",
    companions: "Companions",
    cost: "Cost (₹)",
    topMode: "Top mode",
    distance: "Distance",
    totalTrips: "Total trips",
    duration: "Duration",
    modeBreakdown: "Mode breakdown",
    ecoWidgetTitle: "Your Environmental Impact",
    ecoWidgetSub:
      "By choosing sustainable public transit and active commuting via Vazhi, you have offset a significant carbon footprint.",
    trees: "Trees",
    yearlyAbs: "Yearly absorption equiv.",
    phoneCharges: "Phone charges offset",
    general: "General",
    personalization: "Personalization",
    tripPrefs: "Trip Preferences",
    privacyData: "Privacy & Data",
    insights: "Insights & Reports",
    security: "Security",
    lightMode: "Light Mode active",
    darkMode: "Dark Mode active",
    accountStatus: "Account Status",
    anonProfile: "Anonymous Contributor Profile",
    helpSupport: "Help & Support",
    aboutApp: "About Vazhi",
    themePalette: "Theme Palette",
    language: "Language",
    notifications: "Notifications & Reminders",
    units: "Units",
    autoDetect: "Auto-Detection Fallback",
    defaultMode: "Default Transport Mode",
    purposeCats: "Purpose Categories",
    manageCompanions: "Manage Companions",
    dataConsent: "Data Consent Framework",
    sharingPrefs: "Sharing Preferences",
    exportLogs: "Export My Journey Logs",
    locationPerms: "Location Permissions",
    backgroundAggr: "Background Aggregation",
    clearCache: "Clear Local Device Cache",
    travelDiary: "Travel Diary Maps",
    co2Tracker: "CO₂ Footprint Tracker",
    monthlyReport: "Monthly Travel Report",
    twoFactor: "Two-Factor Authentication",
    biometricLock: "Biometric App Lock",
  },
  ml: {
    profile: "പ്രൊഫൈൽ",
    settingsSub: "ക്രമീകരണങ്ങളും മുൻഗണനകളും",
    journeyLog: "യാത്രാ ഡയറി",
    travelHistory: "നിങ്ങളുടെ യാത്രാ ചരിത്രം",
    tripsRecorded: "യാത്രകൾ രേഖപ്പെടുത്തി",
    syncing: "സിങ്ക് ചെയ്യുന്നു...",
    noJourneysYet: "യാത്രകൾ ഒന്നും തന്നെയില്ല",
    startFirstTrip:
      "എക്സ്പ്ലോർ ടാബിൽ നിന്ന് നിങ്ങളുടെ ആദ്യ യാത്ര ആരംഭിക്കുക, നിങ്ങളുടെ യാത്രകൾ ഇവിടെ ദൃശ്യമാകും.",
    recentJourneys: "സമീപകാല യാത്രകൾ",
    deleteTripTitle: "യാത്ര ഒഴിവാക്കണോ?",
    deleteTripSub: "ഇത് മാറ്റാൻ സാധ്യമല്ല.",
    cancel: "റദ്ദാക്കുക",
    delete: "ഒഴിവാക്കുക",
    logTrip: "യാത്ര രേഖപ്പെടുത്തുക",
    searchDestinations: "ലക്ഷ്യസ്ഥാനങ്ങൾ തിരയുക...",
    origin: "തുടങ്ങുന്ന സ്ഥലം",
    destination: "ലക്ഷ്യസ്ഥാനം",
    satellite: "സാറ്റലൈറ്റ്",
    map: "ഭൂപടം",
    journeyInProgress: "യാത്ര പുരോഗമിക്കുന്നു",
    startJourney: "യാത്ര ആരംഭിക്കുക",
    endJourney: "യാത്ര അവസാനിപ്പിക്കുക",
    tripDetails: "യാത്ര വിവരങ്ങൾ",
    fillTripInfo: "യാത്രാ വിവരങ്ങൾ പൂരിപ്പിക്കുക",
    from: "എവിടെനിന്ന്",
    to: "എവിടേക്ക്",
    enterFrom: "തുടങ്ങുന്ന സ്ഥലം നൽകുക",
    enterTo: "ലക്ഷ്യസ്ഥാനം നൽകുക",
    skipForNow: "ഇപ്പൊഴത്തേക്ക് ഒഴിവാക്കുക",
    saveJourney: "യാത്ര സേവ് ചെയ്യുക",
    missingInfo: "വിവരങ്ങൾ അപൂർണ്ണമാണ്",
    selectModeAlert: "ദയവായി ഒരു യാത്രാ മാർഗ്ഗം തിരഞ്ഞെടുക്കുക.",
    journeyLoggedTitle: "യാത്ര രേഖപ്പെടുത്തി! 🎉",
    awardXpMsg:
      "വഴി വഴി യാത്രാ വിവരങ്ങൾ വിജയകരമായി രേഖപ്പെടുത്തിയിട്ടുണ്ട്.\n\nഈ യാത്രാ മാർഗ്ഗം തിരഞ്ഞെടുത്തതിന് നിങ്ങൾക്ക് +{points} XP ലഭിച്ചിരിക്കുന്നു.",
    transportMode: "യാത്രാ മാർഗ്ഗം",
    tripPurpose: "യാത്രാ ഉദ്ദേശ്യം",
    frequencyQuestion: "നിങ്ങൾ എത്ര തവണ ഈ യാത്ര നടത്താറുണ്ട്?",
    companions: "കൂടെയുള്ളവർ",
    cost: "ചെലവ് (₹)",
    topMode: "കൂടുതൽ ഉപയോഗിച്ചവ",
    distance: "ദൂരം",
    totalTrips: "ആകെ യാത്രകൾ",
    duration: "സമയം",
    modeBreakdown: "യാത്രകളുടെ തരംതിരിവ്",
    ecoWidgetTitle: "പരിസ്ഥിതി ആഘാത റിപ്പോർട്ട്",
    ecoWidgetSub:
      "വഴിയിലൂടെ പൊതുഗതാഗതവും നടപ്പും സൈക്ലിംഗും തിരഞ്ഞെടുത്തതിലൂടെ, നിങ്ങൾ വലിയ തോതിൽ കാർബൺ പുറന്തള്ളൽ കുറച്ചിരിക്കുന്നു.",
    trees: "വൃക്ഷങ്ങൾ",
    yearlyAbs: "വാർഷിക ആഗിരണത്തിന് തുല്യം",
    phoneCharges: "ഫോൺ ചാർജ്ജ് ലാഭിച്ചു",
    general: "പൊതുവായവ",
    personalization: "വ്യક્તિഗതമാക്കൽ",
    tripPrefs: "യാത്രാ മുൻഗണനകൾ",
    privacyData: "സ്വകാര്യതയും വിവരങ്ങളും",
    insights: "റിപ്പോർട്ടുകൾ",
    security: "സുരക്ഷ",
    lightMode: "ലൈറ്റ് മോഡ് സജീവം",
    darkMode: "ഡാർക്ക് മോഡ് സജീവം",
    accountStatus: "അക്കൗണ്ട് നില",
    anonProfile: "അജ്ഞാത സംഭാവന പ്രൊഫൈൽ",
    helpSupport: "സഹായവും പിന്തുണയും",
    aboutApp: "വഴിയെക്കുറിച്ച്",
    themePalette: "തീം പാലറ്റ്",
    language: "ഭാഷ",
    notifications: "അറിയിപ്പുകളും ഓർമ്മപ്പെടുത്തലുകളും",
    units: "യൂണിറ്റുകൾ",
    autoDetect: "ഓട്ടോമാറ്റിക് ഡിറ്റക്ഷൻ",
    defaultMode: "ഡിഫോൾട്ട് യാത്രാ മാർഗ്ഗം",
    purposeCats: "യാത്രാ ഉദ്ദേശ്യങ്ങൾ",
    manageCompanions: "കൂടെയുള്ള യാത്രക്കാർ",
    dataConsent: "വിവര സമ്മത പത്രം",
    sharingPrefs: "പнкиടൽ മുൻഗണനകൾ",
    exportLogs: "യാത്രാ വിവരങ്ങൾ എക്സ്പോർട്ട് ചെയ്യുക",
    locationPerms: "ലൊക്കേഷൻ അനുമതികൾ",
    backgroundAggr: "ബാക്ക്ഗ്രൗണ്ട് ട്രാക്കിംഗ്",
    clearCache: "കാഷെ മായ്ച്ചുകളയുക",
    travelDiary: "യാത്രാ ഡയറി ഭൂപടം",
    co2Tracker: "CO₂ കാർബൺ ട്രാക്കർ",
    monthlyReport: "പ്രതിമാസ യാത്രാ റിപ്പോർട്ട്",
    twoFactor: "ടു-ഫാക്ടർ ഓതന്റിക്കേഷൻ",
    biometricLock: "ബയോമെട്രിക് ആപ്പ് ലോക്ക്",
  },
  ta: {
    profile: "சுயவிவரம்",
    settingsSub: "அமைப்புகள் மற்றும் விருப்பத்தேர்வுகள்",
    journeyLog: "பயணப் பதிவு",
    travelHistory: "உங்கள் பயண வரலாறு",
    tripsRecorded: "பயணங்கள் பதிவு செய்யப்பட்டுள்ளன",
    syncing: "ஒத்திசைக்கப்படுகிறது...",
    noJourneysYet: "இன்னும் பயணங்கள் இல்லை",
    startFirstTrip:
      "ஆராய்வு தாவலில் இருந்து உங்கள் முதல் பயணத்தைத் தொடங்குங்கள், உங்கள் பயணங்கள் இங்கே தோன்றும்.",
    recentJourneys: "சமீபத்திய பயணங்கள்",
    deleteTripTitle: "பயணத்தை நீக்கவா?",
    deleteTripSub: "இதை மாற்ற முடியாது.",
    cancel: "ரத்து செய்",
    delete: "நீக்கு",
    logTrip: "Bபயணத்தை பதிவுசெய்",
    searchDestinations: "இலக்குகளைத் தேடுங்கள்...",
    origin: "தொடக்க இடம்",
    destination: "இலக்கு",
    satellite: "செயற்கைக்கோள்",
    map: "வரைபடம்",
    journeyInProgress: "பயணம் செயலில் உள்ளது",
    startJourney: "Bபயணத்தைத் தொடங்கு",
    endJourney: "பயணத்தை முடி",
    tripDetails: "பயண விவரங்கள்",
    fillTripInfo: "Bஉங்கள் பயண விவரங்களை நிரப்பவும்",
    from: "இருந்து",
    to: "அடைவிடம்",
    enterFrom: "தொடக்க இடத்தை உள்ளிடவும்",
    enterTo: "இலக்கை உள்ளிடவும்",
    skipForNow: "இப்போதைக்குத் தவிர்",
    saveJourney: "பயணத்தைச் சேமி",
    missingInfo: "தகவல் இல்லை",
    selectModeAlert: "போக்குவரத்து முறையைத் தேர்ந்தெடுக்கவும்.",
    journeyLoggedTitle: "Bபயணம் பதிவு செய்யப்பட்டது! 🎉",
    awardXpMsg:
      "வழி வழியாக பயண விவரங்கள் வெற்றிகரமாக பதிவு செய்யப்பட்டன.\n\nஇந்த போக்குவரத்து முறையைத் தேர்ந்தெடுத்ததற்காக உங்களுக்கு +{points} XP வழங்கப்பட்டுள்ளது.",
    transportMode: "போக்குவரத்து முறை",
    tripPurpose: "பயண நோக்கம்",
    frequencyQuestion: "இந்த பயணத்தை நீங்கள் எவ்வளவு அடிக்கடி செய்கிறீர்கள்?",
    companions: "துணை பயணிகள்",
    cost: "Bசெலவு (₹)",
    topMode: "முக்கிய முறை",
    distance: "தூரம்",
    totalTrips: "Bமொத்த பயணங்கள்",
    duration: "கால அளவு",
    modeBreakdown: "முறை முறிவு",
    ecoWidgetTitle: "Bஉங்கள் சுற்றுச்சூழல் தாக்கம்",
    ecoWidgetSub:
      "வழியின் மூலம் நிலையான பொதுப் போக்குவரத்து மற்றும் நடைப்பயணத்தைத் தேர்ந்தெடுத்ததன் மூலம், நீங்கள் கணிசமான கார்பன் அளவைக் குறைத்துள்ளீர்கள்.",
    trees: "மரங்கள்",
    yearlyAbs: "வருடாந்திர உறிஞ்சுதலுக்கு சமம்",
    phoneCharges: "சேமிக்கப்பட்ட போன் சார்ஜ்கள்",
    general: "Bபொதுவானவை",
    personalization: "தனிப்பயனாக்கம்",
    tripPrefs: "Bபயண விருப்பத்தேர்வுகள்",
    privacyData: "தனியுரிமை மற்றும் தரவு",
    insights: "நுண்ணறிவு மற்றும் அறிக்கைகள்",
    security: "பாதுகாப்பு",
    lightMode: "லைட் பயன்முறை செயலில் உள்ளது",
    darkMode: "டார்க் பயன்முறை செயலில் உள்ளது",
    accountStatus: "கணக்கு நிலை",
    anonProfile: "அநாமதேய பங்களிப்பாளர் சுயவிவரம்",
    helpSupport: "Bஉதவி மற்றும் ஆதரவு",
    aboutApp: "வழி பற்றி",
    themePalette: "வண்ண தீம்",
    language: "மொழி",
    notifications: "அறிவிப்புகள் மற்றும் நினைவூட்டல்கள்",
    units: "அலகுகள்",
    autoDetect: "தானியங்கி கண்டறிதல்",
    defaultMode: "Bஇயல்புநிலை போக்குவரத்து முறை",
    purposeCats: "பயண நோக்கங்கள்",
    manageCompanions: "கூட பயணிப்போரை நிர்வகி",
    dataConsent: "Bதரவு ஒப்புதல் கட்டமைப்பு",
    sharingPrefs: "Bபகிர்வு விருப்பத்தேர்வுகள்",
    exportLogs: "பயணப் பதிவுகளை ஏற்றுமதி செய்",
    locationPerms: "Bஇருப்பிட அனுமதிகள்",
    backgroundAggr: "பின்னணி கண்காணிப்பு",
    clearCache: "Bதற்காலிக சேமிப்பை அழி",
    travelDiary: "பயண நாட்குறிப்பு வரைபடம்",
    co2Tracker: "கார்பன் தடம் கண்காணிப்பு",
    monthlyReport: "Bமாதாந்திர பயண அறிக்கை",
    twoFactor: "இருபடி அங்கீகாரம்",
    biometricLock: "கைரேகை ஆப் லாக்",
  },
  hi: {
    profile: "प्रोफ़ाइल",
    settingsSub: "सेटिंग्स और प्राथमिकताएं",
    journeyLog: "यात्रा लॉग",
    travelHistory: "आपका यात्रा इतिहास",
    tripsRecorded: "यात्राएं रिकॉर्ड की गईं",
    syncing: "सिंक हो रहा है...",
    noJourneysYet: "अभी तक कोई यात्रा नहीं",
    startFirstTrip:
      "एक्सप्लोर टैब से अपनी पहली यात्रा शुरू करें और आपकी यात्राएं यहां दिखाई देंगी।",
    recentJourneys: "हाल की यात्राएं",
    deleteTripTitle: "यात्रा हटाएं?",
    deleteTripSub: "यह बदला नहीं जा सकता।",
    cancel: "रद्द करें",
    delete: "हटाएं",
    logTrip: "यात्रा लॉग करें",
    searchDestinations: "गंतव्य खोजें...",
    origin: "प्रारंभिक स्थान",
    destination: "गंतव्य",
    satellite: "सैटेलाइट",
    map: "मानचित्र",
    journeyInProgress: "यात्रा प्रगति पर है",
    startJourney: "यात्रा शुरू करें",
    endJourney: "यात्रा समाप्त करें",
    tripDetails: "यात्रा विवरण",
    fillTripInfo: "अपनी यात्रा की जानकारी भरें",
    from: "कहाँ से",
    to: "कहाँ तक",
    enterFrom: "प्रारंभिक स्थान दर्ज करें",
    enterTo: "गंतव्य दर्ज करें",
    skipForNow: "अभी छोड़ें",
    saveJourney: "यात्रा सहेजें",
    missingInfo: "अधूरी जानकारी",
    selectModeAlert: "कृपया परिवहन का साधन चुनें।",
    journeyLoggedTitle: "यात्रा दर्ज की गई! 🎉",
    awardXpMsg:
      "वज़ि के माध्यम से यात्रा का विवरण सफलतापूर्वक दर्ज किया गया।\n\nइस परिवहन साधन को चुनने के लिए आपको +{points} XP दिए गए हैं।",
    transportMode: "परिवहन मोड",
    tripPurpose: "यात्रा का उद्देश्य",
    frequencyQuestion: "आप यह यात्रा कितनी बार करते हैं?",
    companions: "सह-यात्री",
    cost: "लागत (₹)",
    topMode: "शीर्ष मोड",
    distance: "दूरी",
    totalTrips: "कुल यात्राएं",
    duration: "अवधि",
    modeBreakdown: "परिवहन विभाजन",
    ecoWidgetTitle: "आपका पर्यावरणीय प्रभाव",
    ecoWidgetSub:
      "वज़ि के माध्यम से सतत सार्वजनिक परिवहन & पैदल चलना चुनकर, आपने कार्बन उत्सर्जन काफी कम किया है।",
    trees: "पेड़",
    yearlyAbs: "वार्षिक अवशोषण के बराबर",
    phoneCharges: "बचाए गए फोन चार्ज",
    general: "सामान्य",
    personalization: "व्यक्तिगतकरण",
    tripPrefs: "यात्रा प्राथमिकताएं",
    privacyData: "गोपनीयता & डेटा",
    insights: "अंतर्दृष्टि और रिपोर्ट",
    security: "सुरक्षा",
    lightMode: "लाइट मोड सक्रिय",
    darkMode: "डार्क मोड सक्रिय",
    accountStatus: "खाता स्थिति",
    anonProfile: "अनाम योगदानकर्ता प्रोफ़ाइल",
    helpSupport: "सहायता और समर्थन",
    aboutApp: "वाज़ि के बारे में",
    themePalette: "थीम पैलेट",
    language: "भाषा",
    notifications: "अधिसूचना और अनुस्मारक",
    units: "इकाइयाँ",
    autoDetect: "ऑटो-डिटेक्शन फ़ॉलबैक",
    defaultMode: "डिफ़ॉल्ट परिवहन मोड",
    purposeCats: "उद्देश्य श्रेणियां",
    manageCompanions: "सह-यात्रियों का प्रबंधन",
    dataConsent: "डेटा सहमति ढांचा",
    sharingPrefs: "साझाकरण प्राथमिकताएं",
    exportLogs: "यात्रा लॉग निर्यात करें",
    locationPerms: "स्थान अनुमतियां",
    backgroundAggr: "पृष्ठभूमि एकत्रीकरण",
    clearCache: "स्थानीय कैश साफ़ करें",
    travelDiary: "यात्रा डायरी मानचित्र",
    co2Tracker: "CO₂ फुटप्रिंट ट्रैकर",
    monthlyReport: "मासिक यात्रा रिपोर्ट",
    twoFactor: "दो-चरण प्रमाणीकरण",
    biometricLock: "बायोमेट्रिक ऐप锁",
  },
  ja: {
    profile: "プロフィール",
    settingsSub: "設定と個人設定",
    journeyLog: "移動ログ",
    travelHistory: "移動履歴",
    tripsRecorded: "件の記録された移動",
    syncing: "同期中...",
    noJourneysYet: "履歴がありません",
    startFirstTrip:
      "マップから最初の移動を開始すると、ここに履歴が表示されます。",
    recentJourneys: "最近の移動履歴",
    deleteTripTitle: "履歴を削除しますか？",
    deleteTripSub: "この操作は取り消せません。",
    cancel: "キャンセル",
    delete: "削除",
    logTrip: "手動記録",
    searchDestinations: "目的地を検索...",
    origin: "出発地",
    destination: "目的地",
    satellite: "航空写真",
    map: "地図",
    journeyInProgress: "移動を追跡中",
    startJourney: "追跡を開始",
    endJourney: "追跡を終了",
    tripDetails: "移動の詳細入力",
    fillTripInfo: "移動情報を入力してください",
    from: "出発地",
    to: "目的地",
    enterFrom: "出発地を入力してください",
    enterTo: "目的地を入力してください",
    skipForNow: "後で入力する",
    saveJourney: "移動を保存する",
    missingInfo: "未入力の項目",
    selectModeAlert: "移動手段を選択してください。",
    journeyLoggedTitle: "移動を記録しました！ 🎉",
    awardXpMsg:
      "Vazhi経由で移動ルートが正常に記録されました。\n\nエコな移動手段 of 選択により、+{points} XPが獲得されました。",
    transportMode: "移動手段",
    tripPurpose: "移動の目的",
    frequencyQuestion: "このルートをどのくらいの頻度で移動しますか？",
    companions: "同行者数",
    cost: "費用 (₹)",
    topMode: "主な手段",
    distance: "距離",
    totalTrips: "総移動数",
    duration: "所要時間",
    modeBreakdown: "移動手段の割合",
    ecoWidgetTitle: "環境への貢献度",
    ecoWidgetSub:
      "Vazhiを利用して公共交通機関や徒歩、自転車を選択したことで、二酸化炭素の排出量を大幅に削減できました。",
    trees: "樹木換算",
    yearlyAbs: "年間のCO₂吸収量相当",
    phoneCharges: "スマホ充電削減回数",
    general: "全般",
    personalization: "カスタマイズ",
    tripPrefs: "移動の好みの設定",
    privacyData: "プライバシーとデータ",
    insights: "インサイトとレポート",
    security: "セキュリティ",
    lightMode: "ライトモード有効",
    darkMode: "ダークモード有効",
    accountStatus: "アカウントステータス",
    anonProfile: "匿名貢献者プロフィール",
    helpSupport: "ヘルプとサポート",
    aboutApp: "Vazhiについて",
    themePalette: "テーマパレット",
    language: "言語",
    notifications: "通知とリマインダー",
    units: "単位設定",
    autoDetect: "自動検知フォールバック",
    defaultMode: "デフォルト移動モード",
    purposeCats: "移動目的のカテゴリ",
    manageCompanions: "同行者の管理",
    dataConsent: "データ同意規約",
    sharingPrefs: "データ共有設定",
    exportLogs: "走行ログの書き出し",
    locationPerms: "位置情報の権限",
    backgroundAggr: "バックグラウンド追跡",
    clearCache: "キャッシュデータの削除",
    travelDiary: "トラベルダイアリーマップ",
    co2Tracker: "CO₂足跡トラッカー",
    monthlyReport: "月間移動レポート",
    twoFactor: "2要素認証",
    biometricLock: "生体認証アプリロック",
  },
  ko: {
    profile: "프로필",
    settingsSub: "설정 및 기본 설정",
    journeyLog: "여정 로그",
    travelHistory: "귀하의 이동 기록",
    tripsRecorded: "개의 기록된 여정",
    syncing: "동기화 중...",
    noJourneysYet: "이동 기록이 없습니다",
    startFirstTrip: "탐색 탭에서 첫 이동을 시작하면 여기에 기록이 표시됩니다.",
    recentJourneys: "최근 여정",
    deleteTripTitle: "여정을 삭제하시겠습니까?",
    deleteTripSub: "이 작업은 취소할 수 없습니다.",
    cancel: "취소",
    delete: "삭제",
    logTrip: "기록하기",
    searchDestinations: "목적지 검색...",
    origin: "출발지",
    destination: "목적지",
    satellite: "위성 지도",
    map: "일반 지도",
    journeyInProgress: "여정 추적 중",
    startJourney: "운행 시작",
    endJourney: "운행 종료",
    tripDetails: "이동 상세 정보",
    fillTripInfo: "이동 정보를 입력해주세요",
    from: "출발지",
    to: "목적지",
    enterFrom: "출발지를 입력하세요",
    enterTo: "목적지를 입력하세요",
    skipForNow: "건너뛰기",
    saveJourney: "여정 저장",
    missingInfo: "정보 누락",
    selectModeAlert: "이동 수단을 선택해주세요.",
    journeyLoggedTitle: "여정이 기록되었습니다! 🎉",
    awardXpMsg:
      "Vazhi를 통해 이동 경로가 성공적으로 기록되었습니다.\n\n이 이동 수단을 선택하여 +{points} XP를 획득하셨습니다.",
    transportMode: "이동 수단",
    tripPurpose: "이동 목적",
    frequencyQuestion: "이 경로를 얼마나 자주 이동하십니까?",
    companions: "동행자 수",
    cost: "비용 (₹)",
    topMode: "주요 수단",
    distance: "거리",
    totalTrips: "총 여정 수",
    duration: "소요 시간",
    modeBreakdown: "이동 수단 비율",
    ecoWidgetTitle: "환경적 영향력",
    ecoWidgetSub:
      "Vazhi를 이용해 친환경 대중교통 및 도보, 자전거를 선택함으로써 이산화탄소 배출량을 크게 감축하셨습니다.",
    trees: "소나무",
    yearlyAbs: "연간 이산화탄소 흡수량 상당",
    phoneCharges: "스마트폰 충전 절감 횟수",
    general: "일반",
    personalization: "개인화",
    tripPrefs: "경로 기본 설정",
    privacyData: "개인정보 보호 및 데이터",
    insights: "인사이트 및 보고서",
    security: "보안",
    lightMode: "라이트 모드 활성화",
    darkMode: "다크 모드 활성화",
    accountStatus: "계정 상태",
    anonProfile: "익명 기여자 프로필",
    helpSupport: "도움말 및 지원",
    aboutApp: "Vazhi 소개",
    themePalette: "테마 설정",
    language: "언어",
    notifications: "알림 및 리마인더",
    units: "단위 설정",
    autoDetect: "자동 감지 폴백",
    defaultMode: "기본 이동 수단",
    purposeCats: "이동 목적 카테고리",
    manageCompanions: "동행자 관리",
    dataConsent: "데이터 수집 동의서",
    sharingPrefs: "공유 기본 설정",
    exportLogs: "이동 기록 내보내기",
    locationPerms: "위치 정보 권한",
    backgroundAggr: "백그라운드 추적",
    clearCache: "로컬 캐시 삭제",
    travelDiary: "여행 다이어리 지도",
    co2Tracker: "CO₂ 탄소 발자국 추적",
    monthlyReport: "월간 이동 보고서",
    twoFactor: "2단계 인증",
    biometricLock: "바이오메트릭 앱 잠금",
  },
};

export const LANGUAGE_OPTIONS = [
  { code: "en", label: "English", sub: "English" },
  { code: "ml", label: "മലയാളം", sub: "Malayalam" },
  { code: "ta", label: "தமிழ்", sub: "Tamil" },
  { code: "hi", label: "हिन्दी", sub: "Hindi" },
  { code: "ja", label: "日本語", sub: "Japanese" },
  { code: "ko", label: "한국어", sub: "Korean" },
] as const;

export type LanguageType = keyof typeof TRANSLATIONS;
